# Generated by Django 5.2.17 on 2026-09-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_homework_syllabus_submission'),
        ('staff', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_lunch', models.BooleanField(default=False, help_text='Teacher prefers to teach this subject after lunch.')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_preferences', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_preferences', to='staff.staff')),
            ],
            options={
                'ordering': ['teacher', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('available', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_availability', to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Teacher availabilities',
                'ordering': ['teacher', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'weekday'), name='unique_teacher_weekday')],
            },
        ),
    ]
