# Generated by Django 5.2.17 on 2026-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_homework_syllabus_submission'),
        ('staff', '0001_initial'),
        ('timetable', '0002_teacherpreference_teacheravailability'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_timetable_cell',
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable', 'weekday', 'period', 'klass'), name='unique_timetable_cell'),
        ),
    ]
