# Generated by Django 5.2.17 on 2026-09-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destination_path', models.CharField(help_text='Full folder path. Supports local disks, USB/external HDD drives (e.g. E:\\backups) and network shares (UNC paths, e.g. \\\\server\\edflow_backup).', max_length=500)),
                ('keep_count', models.PositiveIntegerField(default=5, help_text='Number of most recent backups to keep for this profile; older archives are deleted. 0 keeps everything.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('pre_restore', 'Pre-restore safety'), ('automatic', 'Automatic')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('verifying', 'Verifying')], default='running', max_length=12)),
                ('archive_name', models.CharField(blank=True, max_length=255)),
                ('archive_path', models.CharField(blank=True, max_length=600)),
                ('archive_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 of the archive', max_length=64)),
                ('database_file', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('entries', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='backup.backupprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
