# Generated by Django 5.2.17 on 2026-09-23 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency number for this guardian (spec §6).', max_length=20),
        ),
        migrations.AddField(
            model_name='parent',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional Django account so this guardian can log into the parent portal (spec §4).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
