# Generated by Django 5.2.17 on 2026-09-22 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0002_alter_student_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('student_id_card', 'Student ID Card'), ('staff_id_card', 'Staff ID Card'), ('admission_letter', 'Admission Letter'), ('bonafide_certificate', 'Bonafide Certificate'), ('character_certificate', 'Character Certificate'), ('leaving_certificate', 'Leaving Certificate'), ('fee_receipt', 'Fee Receipt')], max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('body', models.TextField(default='', help_text='Body text with placeholders like {student_name}, {admission_number}, {class_name}, {school_name}, {date}.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['doc_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('student_id_card', 'Student ID Card'), ('staff_id_card', 'Staff ID Card'), ('admission_letter', 'Admission Letter'), ('bonafide_certificate', 'Bonafide Certificate'), ('character_certificate', 'Character Certificate'), ('leaving_certificate', 'Leaving Certificate'), ('fee_receipt', 'Fee Receipt')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(blank=True, upload_to='documents/generated/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='staff.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='students.student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
