# Generated by Django 5.2.17 on 2026-09-21 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0002_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='staff_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_houses', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='house',
            name='vice_captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_captained_houses', to='students.student'),
        ),
    ]
