# Generated by Django 5.2.17 on 2026-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='bank_holder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank Name'),
        ),
    ]
