# Generated by Django 5.2.17 on 2026-09-21 13:36

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_initial'),
        ('students', '0002_alter_student_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issued_on', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='students.student')),
            ],
            options={
                'ordering': ['-issued_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_items', to='fees.feehead')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feevoucher')),
            ],
            options={
                'unique_together': {('voucher', 'fee_head')},
            },
        ),
    ]
