# Generated by Django 5.2.17 on 2026-09-22 11:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feevoucher_feevoucheritem'),
        ('students', '0002_alter_student_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concession_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('concession', 'Concession'), ('discount', 'Discount')], default='concession', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage off the (net) amount, e.g. 25.00 for 25%.', max_digits=5, null=True)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount off per applicable fee head.', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fee_heads', models.ManyToManyField(blank=True, related_name='concessions', to='fees.feehead')),
            ],
            options={
                'verbose_name': 'Scholarship / Concession',
                'verbose_name_plural': 'Scholarships & Concessions',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(default=datetime.date.today)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fees.concession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('concession', 'student', 'starts_on'), name='unique_student_concession_period')],
            },
        ),
    ]
