# Generated by Django 5.2.17 on 2026-09-22 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('students', '0002_alter_student_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioninquiry',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='applied_on',
            field=models.DateField(blank=True, help_text='Date the application was submitted.', null=True),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='enrolled_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_inquiry', to='students.student'),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='interview_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='test_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('report_card', 'Previous Report Card'), ('transfer_certificate', 'Transfer Certificate'), ('passport_photo', 'Passport Photos'), ('health_records', 'Health / Immunisation Records'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(blank=True, upload_to='admissions/docs/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissioninquiry')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
