# Generated by Django 5.2.17 on 2026-09-22 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(choices=[('gateway', 'Android Communication Gateway'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('biometric', 'Biometric / fingerprint reader'), ('projector', 'Projector'), ('desktop', 'Desktop / workstation'), ('other', 'Other')], default='gateway', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('maintenance', 'In maintenance'), ('retired', 'Retired')], default='active', max_length=15)),
                ('connection', models.CharField(choices=[('usb', 'USB'), ('lan', 'LAN / Ethernet'), ('wlan', 'Wi-Fi'), ('bluetooth', 'Bluetooth'), ('adb', 'ADB / debug')], default='lan', max_length=12)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('location', models.CharField(blank=True, help_text='e.g. ICT office', max_length=120)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('sim_info', models.CharField(blank=True, max_length=120)),
                ('network_status', models.CharField(blank=True, max_length=120)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, help_text='Battery %, gateway only', null=True)),
                ('gateway_token', models.CharField(blank=True, editable=False, help_text='Secret the Android app presents via X-Gateway-Token.', max_length=64)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='hardware_de_status_687db6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('registered', 'Registered'), ('heartbeat', 'Heartbeat'), ('sms_sent', 'SMS sent'), ('sms_failed', 'SMS failed'), ('result', 'Message result'), ('error', 'Error')], default='heartbeat', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hardware.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='hardware_de_device__a23445_idx')],
            },
        ),
    ]
